name: medal-gestion-sistema

services:

# Bases de datos.
  medal-bdd-postgres:
    container_name: dbMedal
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - medalnetwork


# REDIS para la cola de mensajes
  redis:
    image: redis:8.6.1
    container_name: redis_queue
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379" # Si quieres que sea accesible desde otra ip quitar el 127.0.0.1
    volumes:
      - redis_data:/data
    networks:
      - medalnetwork
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5



# Sistema de la api general.
  medal-api-core:
    container_name: apiMedal
    build: ./api-core
    restart: always
    depends_on:
      medal-bdd-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${API_PORT_EXTERNAL}:${PORT}"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@medal-bdd-postgres:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - medalnetwork
    env_file:
      - .env

# Servicio para las operaciones pesadas del monitoreo.
  medal-worker:
    container_name: workerMedal
    build: ./worker
    environment:
      API_URL: http://medal-api-core:8080
    networks:
      - medalnetwork


# Servicio para el almacenado de los documentos firmados.

  medal-storage:
    container_name: storageMedal
    build: ./storage-service
    volumes:
      - ./storage/firmas:/app/data/pdfs
    networks:
      - medalnetwork


# Frontend:
  medal-frontend:
    container_name: webMedal
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - medal-api-core
    networks:
      - medalnetwork
volumes:
  pgdata_volume:
  redis_data:


networks:
  medalnetwork:
    driver: bridge
